In [1]:
import numpy as np

In [2]:
np.__version__  #to know the numpy version

'1.16.5'

In [7]:
a=[10,20,30,40,50]  #list
print(a)
b=np.array(a)  #b-array
print(b)

[10, 20, 30, 40, 50]
[10 20 30 40 50]


In [8]:
b+100 #adding 100 to the array elements

array([110, 120, 130, 140, 150])

In [9]:
print(b) #no change after adding 100 

[10 20 30 40 50]


In [10]:
b=b+100 #added 100 to the array

In [11]:
print(b)

[110 120 130 140 150]


In [13]:
b.shape #no of rows,no of cols shape only work for arrays not lists

(5,)

In [14]:
b.dtype #attribute to check internal data type i.e..110,120..are int datatype

dtype('int32')

In [19]:
c=[11.5,12.5,13.5,14.5]
c=np.array(c)
c.dtype

dtype('float64')

In [23]:
a=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=1) #ndmin=1 is one row
print(a)
a.shape

[ 1  2  3  4  5  6  7  8  9 10]


(10,)

In [25]:
a=np.array([1,2,3,4,5,6,7,8,9,10],dtype=complex) #complex numbers
print(a)
a.dtype

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]


dtype('complex128')

In [34]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
a.shape #(2,2,3):2-matrices 2-rows 3-columns

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


(2, 2, 3)

In [38]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
a.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [40]:
a=np.array([[1,2,3],[4,5,6]])
print("before shaping")
print(a) #2x3 array
a.shape= (3,2)
print('after shaping')
print(a) #3x2 array

before shaping
[[1 2 3]
 [4 5 6]]
after shaping
[[1 2]
 [3 4]
 [5 6]]


In [42]:
a=np.array([[1,2,3],[4,5,6]])
print("before reshaping")
print(a)
a=a.reshape(3,2)
print('after reshaping')
print(a)

before reshaping
[[1 2 3]
 [4 5 6]]
after reshaping
[[1 2]
 [3 4]
 [5 6]]


In [43]:
print(a.ndim) #no of dimensions

2


In [49]:
np.ones([3,2],dtype=int) #ones-1 zeros-0

array([[1, 1],
       [1, 1],
       [1, 1]])

In [55]:
print(np.arange(5,10,2))

[5 7 9]


In [60]:
print(np.linspace(1,11,2,dtype=int))

[ 1 11]


In [63]:
print(np.linspace(1,11,5))


[ 1.   3.5  6.   8.5 11. ]


In [67]:
print(np.linspace(1,21,10,endpoint=False))

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.]


In [68]:
print(np.linspace(1,21,10,endpoint=True))

[ 1.          3.22222222  5.44444444  7.66666667  9.88888889 12.11111111
 14.33333333 16.55555556 18.77777778 21.        ]


In [69]:
print(np.linspace(1,21,10,retstep=True))

(array([ 1.        ,  3.22222222,  5.44444444,  7.66666667,  9.88888889,
       12.11111111, 14.33333333, 16.55555556, 18.77777778, 21.        ]), 2.2222222222222223)


In [72]:
a=np.array(['ds','ml','ai','dss','iot'])
print(a)
a[2:6]

['ds' 'ml' 'ai' 'dss' 'iot']


array(['ai', 'dss', 'iot'], dtype='<U3')

In [75]:
a.ndim #dimension of the array 'a'

1

In [78]:
a=np.array([1,2,3,4,5])
b=np.array([10,20,30,40,50])
print(a+b) #adding elementwise only if both arrays ae of same no of elements

[11 22 33 44 55]


In [80]:
a=np.array([[1,2,3,4,5],[6,7,8,9,8]])
b=np.array([10,20,30,40,50])
print(a+b)

[[11 22 33 44 55]
 [16 27 38 49 58]]


In [81]:
a.T  #transpose of an array

array([[1, 6],
       [2, 7],
       [3, 8],
       [4, 9],
       [5, 8]])

In [82]:
b.T 

array([10, 20, 30, 40, 50])

In [83]:
print("stastastical functions")

stastastical functions


In [84]:
print(np.std(a)) #standard deviation

2.6095976701399777


In [85]:
print(np.std(b))

14.142135623730951


In [87]:
print(np.min(a))

1


In [88]:
print(np.max(a))

9


In [89]:
print(np.mean(a))

5.3


In [90]:
print(np.median(a))

5.5


In [91]:
print(np.std(a))

2.6095976701399777


In [93]:
print(np.power(a,2))

[[ 1  4  9 16 25]
 [36 49 64 81 64]]


In [95]:
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
np.dot(a,b)

array([[ 70, 100],
       [150, 220]])

In [96]:
np.matmul(a,b) #matrix multuplication

array([[ 70, 100],
       [150, 220]])

In [97]:
np.vdot(a,b) #vector dot product

300

In [98]:
np.inner(a,b)  

array([[ 50, 110],
       [110, 250]])

In [99]:
np.linalg.det(a)

-2.0000000000000004

In [100]:
np.random.rand(2,2)

array([[0.48955149, 0.6731812 ],
       [0.3529034 , 0.06624913]])

ValueError: Range cannot be empty (low >= high) unless no samples are taken